### Chart Overrides
nameOverride: ''
fullnameOverride: ''

imagePullSecrets:
  - name: docker-credentials

# Use Self Signed Cert for TLS between private and public service GRPC
mirrorServiceTLS: false

# image:
#   repository: mobilecoin/full-service-mirror
#   tag: ''

image:
  repository: mcrank/full-service-mirror
  tag: 'v3.1.0-testnet'

ledgerValidator:
  enabled: true
  replicaCount: 1
  listenPort: 5554
  # image:
  #   repository: mobilecoin/full-service-mirror
  #   tag: ''
  imagePullPolicy: Always
  podAnnotations:
    fluentbit.io/include: 'true'
  args: []
  # Example args for testnet
  # - /usr/local/bin/mc-validator-service
  # --ledger-db=/data/ledger.db
  # --peer=mc://node1.test.mobilecoin.com/
  # --peer=mc://node2.test.mobilecoin.com/
  # --tx-source-url=https://s3-us-west-1.amazonaws.com/mobilecoin.chain/node1.test.mobilecoin.com/
  # --tx-source-url=https://s3-us-west-1.amazonaws.com/mobilecoin.chain/node2.test.mobilecoin.com/
  #  --listen-uri=insecure-validator://localhost:5554/
  nodeSelector: {}
  tolerations: []
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: app
                operator: In
                values:
                  - full-service
          topologyKey: 'kubernetes.io/hostname'
  persistence:
    enabled: true
    spec:
      storageClassName: fast
      accessModes:
        - 'ReadWriteOnce'
      resources:
        requests:
          storage: 128Gi

fullService:
  enabled: true
  replicaCount: 1
  listenPort: 9090
  # image:
  #   repository: mobilecoin/full-service-mirror
  #   tag: ''
  imagePullPolicy: Always
  podAnnotations:
    fluentbit.io/include: 'true'
  args: []
  # Example args for testnet
  # - /usr/local/bin/full-service
  # - --listen-host=0.0.0.0
  # - --wallet-db=/data/wallet.db
  # - --ledger-db=/data/ledger.db
  # - --peer=mc://node1.test.mobilecoin.com/
  # - --peer=mc://node2.test.mobilecoin.com/
  # - --tx-source-url=https://s3-us-west-1.amazonaws.com/mobilecoin.chain/node1.test.mobilecoin.com/
  # - --tx-source-url=https://s3-us-west-1.amazonaws.com/mobilecoin.chain/node2.test.mobilecoin.com/
  nodeSelector: {}
  tolerations: []
  affinity: {}
  persistence:
    enabled: true
    spec:
      storageClassName: fast
      accessModes:
        - 'ReadWriteOnce'
      resources:
        requests:
          storage: 128Gi

mirrorPrivate:
  replicaCount: 1
  # image:
  #   repository: mobilecoin/full-service-mirror
  #   tag: ''
  imagePullPolicy: Always
  podAnnotations:
    fluentbit.io/include: 'true'
  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}

mirrorPublic:
  replicaCount: 1
  # image:
  #   repository: mobilecoin/full-service-mirror
  #   tag: ''
  httpPort: 9091
  grpcPort: 10080
  grpcTlsPort: 10443
  imagePullPolicy: Always
  podAnnotations:
    fluentbit.io/include: 'true'
  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: app
                operator: In
                values:
                  - mirror-service-private
          topologyKey: 'kubernetes.io/hostname'
