cargo-features = ["resolver"]

[package]
name = "mc-mobilecoind-mirror"
version = "0.1.0"
authors = ["MobileCoin"]
edition = "2018"
resolver = "2"

[[bin]]
name = "mobilecoind-mirror-private"
path = "src/private/main.rs"

[[bin]]
name = "mobilecoind-mirror-public"
path = "src/public/main.rs"

[dependencies]
mc-api = { path = "mobilecoin/api" }
mc-common = { path = "mobilecoin/common", features = ["loggers"] }
mc-mobilecoind-api = { path = "mobilecoin/mobilecoind/api" }
mc-mobilecoind-json = { path = "mobilecoin/mobilecoind-json" }
mc-util-grpc = { path = "mobilecoin/util/grpc" }
mc-util-uri = { path = "mobilecoin/util/uri" }

digest = "0.9.0"
futures = "0.1"
generic-array = "0.12"
grpcio = "0.5.1"
hex = "0.4"
pem = "0.8.1"
protobuf = "2.12"
rand = "0.7"
rocket = { version = "0.4.5", default-features = false }
rocket_contrib = { version = "0.4.5", default-features = false, features = ["json"] }
serde = "1.0"
serde_derive = "1.0"
sha2 = "0.9.1"
structopt = "0.3"

# We need a specific commit since a version supporting reading PEM files has not been officially released yet.
rsa = { git = "https://github.com/RustCrypto/RSA", rev = "4274e838d112a0aa194a2102ed4930fd9797f1eb" }

[build-dependencies]
# Even though this is unused, it needs to be here otherwise Cargo brings in some weird mixture of packages/features that refuses to compile.
# Go figure ¯\_(ツ)_/¯
serde = { version = "1", default-features = false, features = ["alloc", "derive"] }

mc-util-build-grpc = { path = "mobilecoin/util/build/grpc" }
mc-util-build-script = { path = "mobilecoin/util/build/script" }

cargo-emit = "0.1.1"

[patch.crates-io]
prost = { git = "https://github.com/danburkert/prost", rev = "6113789f70b69709820becba4242824b4fb3ffec" }
prost-derive = { git = "https://github.com/danburkert/prost", rev = "6113789f70b69709820becba4242824b4fb3ffec" }
